// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAZkAd60cGw5mMnZ1jALZ7EUW1jtjqmh0',
    appId: '1:318926159367:web:29587eea330cf9b2d6b4a2',
    messagingSenderId: '318926159367',
    projectId: 'timesgaze-41052',
    authDomain: 'timesgaze-41052.firebaseapp.com',
    storageBucket: 'timesgaze-41052.appspot.com',
    measurementId: 'G-1F1LL7RZC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA47Gsryenocs9uGNNJ6eU5M-GLnTBzYVY',
    appId: '1:989810994749:android:2475b198a638c7dab50454',
    messagingSenderId: '989810994749',
    projectId: 'timesgaze-8c00f',
    storageBucket: 'timesgaze-8c00f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYM1usMVnin9ZrKEbaPwwfTsPse0lYZwY',
    appId: '1:318926159367:ios:0dd61ac11f3b9c5bd6b4a2',
    messagingSenderId: '318926159367',
    projectId: 'timesgaze-41052',
    storageBucket: 'timesgaze-41052.appspot.com',
    androidClientId: '318926159367-05r8fo5kr7dliipu3v898ghm7j9sfm3s.apps.googleusercontent.com',
    iosClientId: '318926159367-1uonio91oh4ui7m3j7lp5a8c1q7r9amu.apps.googleusercontent.com',
    iosBundleId: 'com.timesgaze.timesgaze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYM1usMVnin9ZrKEbaPwwfTsPse0lYZwY',
    appId: '1:318926159367:ios:0dd61ac11f3b9c5bd6b4a2',
    messagingSenderId: '318926159367',
    projectId: 'timesgaze-41052',
    storageBucket: 'timesgaze-41052.appspot.com',
    androidClientId: '318926159367-05r8fo5kr7dliipu3v898ghm7j9sfm3s.apps.googleusercontent.com',
    iosClientId: '318926159367-1uonio91oh4ui7m3j7lp5a8c1q7r9amu.apps.googleusercontent.com',
    iosBundleId: 'com.timesgaze.timesgaze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAZkAd60cGw5mMnZ1jALZ7EUW1jtjqmh0',
    appId: '1:318926159367:web:574b04e03dcea9e1d6b4a2',
    messagingSenderId: '318926159367',
    projectId: 'timesgaze-41052',
    authDomain: 'timesgaze-41052.firebaseapp.com',
    storageBucket: 'timesgaze-41052.appspot.com',
    measurementId: 'G-EH1YCXS24N',
  );

}