// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd1sunYst79rX3hTsVpA902BaW0S8mcAY',
    appId: '1:540161251770:web:a2f4fa6738faf472fde583',
    messagingSenderId: '540161251770',
    projectId: 'timesgaze-6076f',
    authDomain: 'timesgaze-6076f.firebaseapp.com',
    storageBucket: 'timesgaze-6076f.firebasestorage.app',
    measurementId: 'G-7QNEW3WGE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnvPq-rw4f1YqvSKXo0QUCUv5bmPeDpbo',
    appId: '1:540161251770:android:422d35c47181652efde583',
    messagingSenderId: '540161251770',
    projectId: 'timesgaze-6076f',
    storageBucket: 'timesgaze-6076f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMLQwiFhoUvNVb0rof4JMOmUiVM1lYVOw',
    appId: '1:540161251770:ios:cc63e6a9741b333cfde583',
    messagingSenderId: '540161251770',
    projectId: 'timesgaze-6076f',
    storageBucket: 'timesgaze-6076f.firebasestorage.app',
    iosBundleId: 'com.timesgaze.timesgaze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMLQwiFhoUvNVb0rof4JMOmUiVM1lYVOw',
    appId: '1:540161251770:ios:cc63e6a9741b333cfde583',
    messagingSenderId: '540161251770',
    projectId: 'timesgaze-6076f',
    storageBucket: 'timesgaze-6076f.firebasestorage.app',
    iosBundleId: 'com.timesgaze.timesgaze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd1sunYst79rX3hTsVpA902BaW0S8mcAY',
    appId: '1:540161251770:web:46eead5b4b0f28e5fde583',
    messagingSenderId: '540161251770',
    projectId: 'timesgaze-6076f',
    authDomain: 'timesgaze-6076f.firebaseapp.com',
    storageBucket: 'timesgaze-6076f.firebasestorage.app',
    measurementId: 'G-9LWQB2DNY2',
  );

}